on: 
  push:
    branches:
      - Ignatius
name: Publish Website
jobs:
  web-deploy:
    name: ğŸš€ Deploy website every commit
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2.1.0
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/web-deploy@master
      with:
        target-server: 103.50.161.248
        remote-user: ignatius2
        remote-key: ${{ secrets.ftp_password }}
        destination-path: /
        rsync-options: --dry-run

